### ISSUE TITLE
Implement BinaryExpression node

### ISSUE THREAD

**Issue by vault-developer** [vault-developer/event-loop-explorer#14]
Currently, if we run this code in the editor
```
console.log(1+1);
```
You will see this error in the console:
![image](https://github.com/user-attachments/assets/51a602d5-fe3f-418e-8bc4-daf9b38625e5)
And in UI we will see an empty section instead of logged result 2:
![image](https://github.com/user-attachments/assets/d1fc13dc-b3ea-4304-9649-fb75b918ed42)

This happens because the logic for managing the `BinaryExpression` node has not yet been implemented.
We would like to handle this issue.

Please check already implemented nodes for the reference:
https://github.com/vault-developer/event-loop-explorer/tree/master/src/utils/nodes

**Comment by harshitkumargupta** [comment]
Hi @vault-developer can you please assign this issue under Hacktoberfest tag.

**Comment by vault-developer** [comment]
Hey @harshitkumargupta , since there have been no updates for over a month, I will put this issue to unassigned again.
Please let me know if you still want to work on this one.

**Comment by vault-developer** [comment]
I'm closing the issue since there are no updates for a long time
