### ISSUE TITLE
Add e2e tests with playwright

### ISSUE THREAD

**Issue by malcodeman** [vault-developer/event-loop-explorer#15]
I think using react testing library would work great for this project. 
I have time to tackle this issue so feel free to assign it to me.

**Comment by vault-developer** [comment]
Hey @malcodeman sorry for the late response.
If you are still interested feel free to take it.
Otherwise feel free to close the issue and I will split it to several tickets for anyone else who is interested 👍

**Comment by malcodeman** [comment]
No worries, I am still interested in making some tests for this project but I was thinking that it might be more valuable to provide e2e tests with Playwright. That way we could test the whole user flow and the UI changes. Let me know what you think.

**Comment by vault-developer** [comment]
Hey @malcodeman,
Thank you for the idea.
I agree, it will be useful as well to cover user flow with e2e.
Feel free to take it if you would like 👍

**Comment by vault-developer** [comment]
Resolved in https://github.com/vault-developer/event-loop-explorer/pull/23
