### ISSUE TITLE
Add margin to modals

### ISSUE THREAD

**Issue by vault-developer** [vault-developer/event-loop-explorer#20]
There is no margin now for modals and it looks not perfect on mobile devices.
We need to add a small margin and keep modal centered vertically and horizontally. 

![image](https://github.com/user-attachments/assets/0aba1da1-e30f-46e2-b27b-f22ce01b7546)

**Comment by VarPDev** [comment]
I opened this pull request: https://github.com/vault-developer/event-loop-explorer/pull/21
