### ISSUE TITLE
Incorrect results for async/await and promise calls

### ISSUE THREAD

**Issue by acherkashin** [vault-developer/event-loop-explorer#27]
The UI looks awesome. I saw different implementation, however this one is the best.

I've played with the tool, however it seems it shows incorrect results for the following code snippet.

```js
async function test1() {
    console.log('start-1');
    return Promise.resolve();
}

async function test2() {
    console.log('start-2');
    return await Promise.resolve();
}

test1().then(() => console.log('done-1'));
test2().then(() => console.log('done-2'));

console.log('end');
```

Output should be 

```
start-1
start-2
end
done-2
done-1
```

However tool shows that `done-1` is executed before `done-2`

**Comment by vault-developer** [comment]
Hey @acherkashin, thank you for raising the issue.
There is a disclaimer in the readme regarding async await and promises support:
https://github.com/vault-developer/event-loop-explorer/blob/master/README.md?plain=1#L27

I wish I had more time to work on it.
Hopefully, someone could take this issue 👍

**Comment by acherkashin** [comment]
@vault-developer got it, thank you 🙏
