### ISSUE TITLE
Add code syntax validation

### ISSUE THREAD

**Issue by vault-developer** [vault-developer/event-loop-explorer#3]
Ace editor is used in the project.
To provide better user experience we wan to add syntax validation via webworker:
https://github.com/ajaxorg/ace/wiki/Syntax-validation

**Comment by vprathap21** [comment]
I'd like to work on this , can you assign me

**Comment by vault-developer** [comment]
Thank you @vprathap21, the issue is assigned to you 👍

**Comment by vault-developer** [comment]
Hey @vprathap21, since there have been no updates for over a month, I will put this issue to unassigned again.
Please let me know if you still want to work on this one.

**Comment by vault-developer** [comment]
I'm closing the issue since there are no updates for a long time
