### ISSUE TITLE
Make mobile layout more user-friendly

### ISSUE THREAD

**Issue by vault-developer** [vault-developer/event-loop-explorer#7]
The current mobile layout looks like this (please check the screenshot);
Therefore, it's not possible for the user to keep all sections in one viewport, and important actions can be missed by user.
We might need to find a way how we can improve UX, so that the application will be useful for mobile devices as well. 
![image](https://github.com/user-attachments/assets/cbaba8b0-4eb5-46cb-a0e5-b9012e0e4be7)

**Comment by Shaiq1217** [comment]
Its understandable to create a responsive layout for smaller screens, but does targeting mobile screens really makes sense. I mean not many people would be writing sample code on mobile screens? Although i agree that the layout needs to be better optimized for smaller laptop screens.

**Comment by vault-developer** [comment]
> Its understandable to create a responsive layout for smaller screens, but does targeting mobile screens really make sense. I mean not many people would be writing sample code on mobile screens? Although i agree that the layout needs to be better optimized for smaller laptop screens.

Hey @Shaiq1217 thank you for the comment. 
I agree it's less convenient to write sample codes from the mobile side.  
However, we can choose from already existing examples. 
If we could improve UX on this perspective it might be useful 👍

**Comment by vault-developer** [comment]
Let's reopen the issue when we have ideas how to handle it better
