### ISSUE TITLE
Add "next step" button with functionality

### ISSUE THREAD

**Issue by vault-developer** [vault-developer/event-loop-explorer#8]
Currently, we have these action buttons:
- start
- stop
- pause
- resume

I received feedback from several engineers, that it might be beneficial to add a "Next step" button.
If the user presses the next step button, the code should be executed until the next step and then paused.
Therefore, they do not miss any particular step due to the speed of the animation.

**Comment by Sapna127** [comment]
hey, I would like to work on this issue. Please assign it to me.

**Comment by vault-developer** [comment]
Hey @Sapna127 thank you, it is assigned to you 👍

**Comment by vault-developer** [comment]
Hey @Sapna127, since there have been no updates for over a month, I will put this issue to unassigned again.
Please let me know if you still want to work on this one.

**Comment by vault-developer** [comment]
I'm closing the issue since there are no updates for a long time
